version: '3.5'
services:
  db:
    image: zlimaa/postgres-projeto-base-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: projeto_base_api
    ports:
      - "5432:5432"
    networks:
      - postgres
  projeto-base-api:
    image: zlimaa/projeto-base-api
    restart: always
    build: ./backend
    working_dir: /backend
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Desenvolvimento
    volumes:
      - ./backend:/backend
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - postgres
networks:
  postgres:
    driver: bridge